---
Standards:
  -
    Title: IPQ 01
    Description: Dynamic Programming
    UID: 6308bf63-d177-4da8-91d3-d4bfa72be1e2
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: 60f8ae34-eaa3-48ff-9d1e-74d8cfb3c71a
        Path: /01/implement-pascals.instructor.md
      -
        Type: Lesson
        UID: f627ccef-7fde-464b-bdf7-5f867dc9de90
        Path: /01/pascals.md
      -
        Type: Checkpoint
        UID: c05ba773-44dc-4891-8e96-35db8e3d8e86
        Path: /01/implement-pascals.checkpoint.md
  -
    Title: IPQ 02
    Description: Linked Lists
    UID: 1d85b30b-724d-4807-900c-1356a5421258
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: 2e82534d-e926-43f6-8cc3-7cf98caa8e08
        Path: /02/implement-intersection.instructor.md
      -
        Type: Lesson
        UID: c41648cf-3e08-4d9e-97d4-7dda6e60feee
        Path: /02/intersection.md
      -
        Type: Checkpoint
        UID: 69d635dc-9cc2-4a56-a2e7-1a8d788b6a13
        Path: /02/implement-intersection.checkpoint.md
  -
    Title: IPQ 03
    Description: Binary Search Trees
    UID: bec82abd-14a6-444a-802b-8b5b591a1e4d
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: 6cb0dbae-118d-4315-a6af-a06730206683
        Path: /02/implement-intersection.instructor.md
      -
        Type: Lesson
        UID: 721dc0f6-a060-4173-bcf1-5039e3661127
        Path: /02/intersection.md
      -
        Type: Checkpoint
        UID: 6691b510-034a-494d-b253-fb5be2fe6186
        Path: /02/implement-intersection.checkpoint.md