---
Standards:
  -
    Title: PSE 01
    Description: Most Frequent K Elements
    UID: 6308bf63-d177-4da8-91d3-d4bfa72be1e2
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: 60f8ae34-eaa3-48ff-9d1e-74d8cfb3c71a
        Path: /01/implement-most-frequent-k-elements.instructor.md
      -
        Type: Lesson
        UID: f627ccef-7fde-464b-bdf7-5f867dc9de90
        Path: /01/most-frequent-k-elements.md
      -
        Type: Checkpoint
        UID: c05ba773-44dc-4891-8e96-35db8e3d8e86
        Path: /01/implement-most-frequent-k-elements.checkpoint.md
  -
    Title: PSE 02
    Description: Linked Lists
    UID: 1d85b30b-724d-4807-900c-1356a5421258
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: 2e82534d-e926-43f6-8cc3-7cf98caa8e08
        Path: /02/implement-intersection.instructor.md
      -
        Type: Lesson
        UID: c41648cf-3e08-4d9e-97d4-7dda6e60feee
        Path: /02/intersection.md
      -
        Type: Checkpoint
        UID: 69d635dc-9cc2-4a56-a2e7-1a8d788b6a13
        Path: /02/implement-intersection.checkpoint.md
  -
    Title: PSE 03
    Description: Binary Search Trees
    UID: bec82abd-14a6-444a-802b-8b5b591a1e4d
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: 6cb0dbae-118d-4315-a6af-a06730206683
        Path: /03/implement-arr-to-bst.instructor.md
      -
        Type: Lesson
        UID: 721dc0f6-a060-4173-bcf1-5039e3661127
        Path: /03/arr-to-bst.md
      -
        Type: Checkpoint
        UID: 6691b510-034a-494d-b253-fb5be2fe6186
        Path: /03/implement-arr-to-bst.checkpoint.md
  -
    Title: PSE 04
    Description: Graphs - DFS & BFS
    UID: aea9e725-c820-41cb-9caa-108b1bf03fb3
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: 76a543ae-4a97-4301-ba2c-d9865301c504
        Path: /04/implement-bipartition-graph.instructor.md
      -
        Type: Lesson
        UID: c6db5932-3f06-4d76-8932-13f61bfa7eb4
        Path: /04/bipartition-graph.md
      -
        Type: Checkpoint
        UID: edfec3f9-1247-444c-9ea5-759d6a4877da
        Path: /04/implement-bipartition-graph.checkpoint.md
  -
    Title: PSE 05
    Description: Dijkstra's Algorithm
    UID: bb35fb6e-c6bc-48cc-aeab-6f5f5cb91afc
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: 40c9f6b2-000b-41a0-ab83-62b2dd92bdab
        Path: /05/implement-network-delay.instructor.md
      -
        Type: Lesson
        UID: a14c29d5-e807-4ba7-b842-427538f99f45
        Path: /05/network-delay.md
      -
        Type: Checkpoint
        UID: 073e27b2-f57d-436f-9560-6afdcbcb6407
        Path: /05/implement-network-delay.checkpoint.md